### ISSUE TITLE
I've tried to compile "Hello, World" example, but "translation" seems to be missing from SpriteBundle. There is a position component, though.

### ISSUE THREAD

**Issue by DanielSolmann** [katharostech/bevy_retrograde#54]
```
error[E0560]: struct `bevy_retrograde::prelude::SpriteBundle` has no field named `transform`
  --> src/main.rs:48:13
   |
48 |             transform: Transform::from_xyz(0., 0., 0.),
   |             ^^^^^^^^^ `bevy_retrograde::prelude::SpriteBundle` does not have this field
   |
   = note: available fields are: `sprite`, `image`, `visible`, `position`, `world_position`
```

**Comment by zicklag** [comment]
Hey there! The code you are trying to compile looks like it's off of the master branch, which isn't published to crates.io yet. You've got a couple of options:

1. You could use the master version of Bevy Retrograde by switching the bevy_retrograde dependency to this in your `Cargo.toml`:
  ```toml
  bevy_retrograde = { git = "https://github.com/katharostech/bevy_retrograde" }
  ```
2. You could look at the example code for our currently released version [here](https://github.com/katharostech/bevy_retrograde/blob/v0.1.0/examples/hello_world.rs)

Because we're going to be releasing a new update soon, and because there are a good set of changes, it would probably be easier for you to just use the git dependency until we get the next release out.

**Comment by DanielSolmann** [comment]
I've deleted and recreated my `Cargo.lock`, seems to work now, thanks.

**Comment by zicklag** [comment]
Glad you got it working! Let me know if you have any more trouble. 🙂
