### ISSUE TITLE
🐞 assertion failed: `!gl_dx_interop_device.is_null()`

### ISSUE THREAD

**Issue by get200** [katharostech/bevy_retrograde#60]
$ cargo run --example hello_world
    Finished dev [optimized] target(s) in 0.38s
     Running `target\debug\examples\hello_world.exe`
thread 'main' panicked at 'assertion failed: !gl_dx_interop_device.is_null()', D:/rust/.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\surfman-0.4.3\src\platform\windows\wgl\device.rs:159:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\hello_world.exe` (exit code: 101)

cargo 1.55.0-nightly
rustc 1.56.0-nightly
Windows 11
Windows Feature Experience Pack 421.18901.0.3

**Comment by zicklag** [comment]
Hey there! Thanks for the report.

I'm not 100% sure, but it looks like your device might not support D3D11, or else there is some error in the way we are trying to initialize the device. As we work on migrating to Bevy's Renderer ( you can subscribe to #41 to track progress ), we will be using a totally different graphics backend that should not have this issue.

Unfortunately it might be a couple months or more before we finish the rendering migration. I'll leave this open until then, though, and let you know when we've got it working!

**Comment by zicklag** [comment]
Good find! Definitely looks like the same issue. Our renderer update should definitely fix it because we won't be using surfman anymore.

Just as an update, I think we will probably be waiting until Bevy 0.6 is released before we get the new renderer merged in to fix this. Bevy 0.6 comes with a totally rewritten renderer and we want to wait until that is released before we try to push out a new version of Bevy Retrograde on top of it.

**Comment by zicklag** [comment]
A new release is coming out soon that switches entirely to Bevy, so this should be fixed. If it isn't fixed, we can open a Bevy issue.
