### ISSUE TITLE
Project development

### ISSUE THREAD

**Issue by boyswan** [katharostech/bevy_retrograde#63]
Just wanted to ask whether the owners are intending to continue development on this project! There are no new features as such that I need, more so asking out of curiosity.

**Comment by zicklag** [comment]
Good question!

Right now we have been slowly chipping away at making the renderer work on top of Bevy ( #41 ) which has taken a bit of effort and also involved us trying to get WGPU working on OpenGL and Web so that we don't lose support for those platforms in Bevy Retrograde.

We are going to be continuing development as we have time but I have gotten very busy lately so I'm not sure how much time I will have for this in the near future.

That said, because Retrograde will be using Bevy's Renderer after we are done with #41, Bevy Retrograde will end up just a simple plugin pack for Bevy, not doing anything fancy for rendering anymore. In that case, I don't know if there were going to end up a lot more features in Bevy Retrograde anyway, now that we've covered map loading, physics, text, and UI. The biggest things we were thinking of adding in the future were and easy save-data plugin and maybe input mapping plugin, but that's about all we've thought of so far.

Out of curiosity, what kind of features were you going to need that aren't in Bevy Retrograde?

---

Anyway, hope that answers your question! Let me know if there's anything else you'd like to know. :D

**Comment by boyswan** [comment]
Thank for the reply! 

I don't think there's much in the sense of features, but a maybe functionality that utilises core parts of the library and abstracts common 2D tasks. For example I'm currently trying to figure out how to get world coords using the retrograde_camera to handle moving a sprite to a particular LDTK tile. Bearing in mind I'm a beginner, I'm not sure whether this would be a bevy task or a bevy_retrograde one.

Perhaps I'm answering my own question here and that this is less of a concern for the library, and more so one for me to figure out!

**Comment by boyswan** [comment]
Thanks for such a detailed reply, much appreciated! 

To be honest I think as bevy_retrograde offers a nice 'starting point' for 2d games, it's less new features and more so functionality that would be most helpful, especially for beginners (such as myself!). There's some basic functionality that I'm trying to implement, and am not sure whether it should be solved in retrograde or bevy.

For example I'm trying to click on

**Comment by zicklag** [comment]
OK, that makes sense! I could definitely see us including features such as that, but those would probably become more integrated as we started to work with our own games and got a feel for what would be commonly needed, and how we might create an easier API for common tasks.

Definitely feel free to create issues with things you think might be nice for Bevy Retrograde to help you with, and even if we don't get to it right away, it will help give us ideas whenever we get the chance. :+1:
